 image: node:18.14.2
 
 pipelines:
   branches:
     master:
      - step:
          name: "Build and Deploy"
          size: 2x
          caches:
            - node
          script:
                  - apt-get update
                  - apt-get install zip
                  - npm cache clean --force
                  - npm install
                  - unset CI 
                  - npm run build
                  - zip -r application.zip build/
                  - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
                    variables:
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION 
                        APPLICATION_NAME : 'luckydraw'
                        ENVIRONMENT_NAME : 'Luckydraw-env'
                        ENVIRONMENT_NAME : 'Luckydraw-env-1'
                        ZIP_FILE : 'application.zip'
                        S3_BUCKET : $S3_BUCKET